version: "3"

services:
  dev:
    image: "node:18"
    volumes:
      - ".:/app"
    working_dir: "/app"
    command: [ "sleep", "infinity" ]

  app:
    image: "node:18"
    volumes:
      - ".:/app"
    working_dir: "/app"
    ports:
      - "3000:3000"
    command: [ "npm", "run", "dev" ]
