version: '3'

services:
  db:
    image: 'postgres:15-alpine'
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: discordweb
      POSTGRES_PASSWORD: password
      POSTGRES_DB: discordweb
      POSTGRES_INITDB_ARGS: '--locale=C --encoding=UTF-8'
  
  migrate:
    image: 'flyway/flyway:9-alpine'
    volumes:
      - ./db/sql:/flyway/sql
    command: '-url=jdbc:postgresql://db/discordweb -user=discordweb -password=password migrate'
    links:
      - db
